In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report

In [28]:
data = pd.read_csv("../datasets/Iris.csv")

In [29]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [30]:
data['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [31]:
species_encodeing = {
    "Iris-setosa": 0,
    "Iris-versicolor":1,
    "Iris-virginica":2
}

In [32]:
data['Species_encoding'] = data['Species'].map(species_encodeing)

In [33]:
data.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Species_encoding
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0

In [34]:
X = data.drop(columns=['Species', 'Species_encoding','Id'])
Y = data['Species_encoding']

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [47]:
md.predict([[5.6,2,0.3, 0.4]])

array([2], dtype=int64)

In [36]:
SS = StandardScaler()

In [37]:
X_train_scaled = SS.fit_transform(X_train)
X_test_scaled = SS.fit_transform(X_test)

In [38]:
mls = {
    "rf": RandomForestClassifier(random_state=42, n_estimators=150),
    "lr": LogisticRegression(random_state=42, solver="saga"),
    "svc": SVC(random_state=42)
}

In [39]:
for model_name, model in mls.items():
    md = model.fit(X_train_scaled, y_train)
    y_pred = md.predict(X_test_scaled)

    clr = classification_report(y_test, y_pred)
    print(f"Model Name: {model_name}")
    print(clr)
    print("----------------------------------------------------------------")

Model Name: rf
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

----------------------------------------------------------------
Model Name: lr
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.85      0.92        13
           2       0.87      1.00      0.93        13

    accuracy                           0.96        45
   macro avg       0.96      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45

----------------------------------------------------------------
Model Name: svc
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.85      0.92        13
           2       0.87      1.00      0.93        13

    accuracy                           0.96        45
   macro avg       0.96      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45

----------------------------------------------------------------

## With pipelining

In [40]:
rf_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("rf", RandomForestClassifier())
])

In [41]:
lr_pipline = Pipeline([
    ("scaler", StandardScaler()),
    ("lr", LogisticRegression())
])

In [42]:
ml_pipline = {
    "rf_pipeline": rf_pipeline,
    "lr_pipeline": lr_pipline
}

In [44]:
for model_pipe, pipeline in ml_pipline.items():
    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)

    clr = classification_report(y_test, y_pred)
    print(f"Model Name: {model_pipe}")
    print(clr)
    print("----------------------------------------------------------------")

Model Name: rf_pipeline
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

----------------------------------------------------------------
Model Name: lr_pipeline
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

----------------------------------------------------------------